name: Go Build Matrix

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            arch: amd64
          - goos: linux
            arch: arm64
          - goos: darwin
            arch: amd64
          - goos: darwin
            arch: arm64
          - goos: windows
            arch: amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    # cache unique per OS/arch
    - name: Cache modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: go-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-${{ runner.os }}-${{ matrix.arch }}-

    - name: Vet & Test
      run: |
        go vet ./...
        go test ./... || true   # remove '|| true' once you add tests

    # -------- compile binary (no zip!) --------
    - name: Build (${{ matrix.goos }}-${{ matrix.arch }})
      id: build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        set -euo pipefail
        EXT=""
        if [ "${GOOS}" = "windows" ]; then EXT=".exe"; fi
        OUT="gitr-${GOOS}-${GOARCH}${EXT}"
        go build -v -o "$OUT" .
        echo "out=$OUT" >> "$GITHUB_OUTPUT"

    # -------- upload binary; artifact action adds the single zip --------
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.out }}   # artifact name
        path: ${{ steps.build.outputs.out }}   # binary file
        if-no-files-found: error

