name: Go Build Matrix

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            arch: amd64
          - goos: linux
            arch: arm64
          - goos: darwin
            arch: amd64
          - goos: darwin
            arch: arm64
          - goos: windows
            arch: amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.1"

    # cache unique per OS/arch
    - name: Cache modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod/${{ matrix.goos }}-${{ matrix.arch }}
          ~/.cache/go-build/${{ matrix.goos }}-${{ matrix.arch }}
        key: go-${{ matrix.goos }}-${{ matrix.arch }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-${{ matrix.goos }}-${{ matrix.arch }}-

    - name: Vet & Test
      run: |
        go vet ./...
        go test ./... || true   # delete '|| true' once you add tests

    # -------- compile binary (constant name) --------
    - name: Build (${{ matrix.goos }}-${{ matrix.arch }})
      id: build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
        GOMODCACHE: ~/go/pkg/mod/${{ matrix.goos }}-${{ matrix.arch }}
        GOCACHE:    ~/.cache/go-build/${{ matrix.goos }}-${{ matrix.arch }}
      run: |
        set -euo pipefail
        EXT=""
        if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
        go build -v -o gitr${EXT} .
        mkdir -p dist/${GOOS}-${GOARCH}
        mv gitr${EXT} dist/${GOOS}-${GOARCH}/gitr${EXT}
        echo "dir=dist/${GOOS}-${GOARCH}" >> $GITHUB_OUTPUT

    # -------- upload folder; action creates single zip --------
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: gitr-${{ matrix.goos }}-${{ matrix.arch }}
        path: ${{ steps.build.outputs.dir }}
        if-no-files-found: error

